/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const LocalSvgIcon: (props: {
    name: "icon-forbidden" | "icon-not-found" | "icon-react" | "icon-server-error"
    className?: string
    style?: React.CSSProperties
  }) => JSX.Element;
  export const svgNames: ["icon-forbidden", "icon-not-found", "icon-react", "icon-server-error"];
  export type SvgName = "icon-forbidden" | "icon-not-found" | "icon-react" | "icon-server-error";
  export default LocalSvgIcon;
}
